name: FrostAndFallout
version: '1.0-SNAPSHOT'
main: dev.lotus.studio.Main
api-version: '1.21'
soft-depend: [Oraxen]
libraries:
  - org.xerial:sqlite-jdbc:3.50.3.0
  - com.j256.ormlite:ormlite-jdbc:6.1
  - com.google.guava:guava:32.0.1-android
commands:
  frostandfallout:
    description: Перезагрузка конфигурации плагина.
    usage: /<command>
    permission: frostandfallout.use
    permission-message: "У вас нет прав для выполнения этой команды."
    aliases: [faf]

permissions:
  frostandfallout.use:
    description: Дозволяє користуватись командою /lotus
    default: true

  frostandfallout.item:
    description: Дозволяє доступ до підкоманди item
    default: op

  frostandfallout.safezone:
    description: Дозволяє доступ до підкоманди safezone
    default: op

  frostandfallout.reload:
    description: Дозволяє виконувати reload
    default: op